# Zenika Papers

// Graph Gist : https://portal.graphgist.org/
// Syntaxe : https://neo4j.com/graphgist/how-to-create-a-graphgist

## Ma 1ère Transaction bancaire

Mot clef : CREATE, RETURN
// Date https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_date_and_time_conversions

[source,cypher]
----
CREATE(t1:Transaction{date:'2017-01-01', destinataire:'Le Houblon Forever', libelle:'Bieres', montant:150.00})
RETURN *
----
//graph

## Plusieurs transactions bancaires

[source,cypher]
----
MERGE(t1:Transaction{date:'2017-01-01', destinataire:'Le Houblon Forever', libelle:'Bieres', montant:150.00})
MERGE(t2:Transaction{date:'2017-01-11', destinataire:'Jouet Club',libelle:'arbre de noel',montant:500.00})
MERGE(t3:Transaction{date:'2017-05-01', destinataire:'Agence Nantes',libelle:'remboursement frais',montant:1000.00})
RETURN *
----

//graph


## Nouvelle entité : bénéficiaires

[source,cypher]
----
MERGE(p1:Personne{nom:'Le Houblon Forever', position:'1 rue Gresset, 44000 Nantes'})
MERGE(p2:Personne{nom:'Ujoodha', prenom:'Vickrame', dateNaissance:'1979-06-21', sexe:'M',compteGithub:'vickrame',compteTwitter:'RuvaChlea',profession:'developpeur', _libelle:'VUJ' })
MERGE(p3:Personne{nom:'Nègre',prenom:'Florian',sexe:'M',compteGithub:'fnegre',compteTwitter:'floriannegre',profession:'developpeur'})
RETURN *
----

//graph


## Relation entre les transactions et les bénéficiaires

mot clef : `-[]->`

[source,cypher]
----
MERGE(transaction1:Transaction{sens:'D', emetteur:'CE', destinataire:'Le Houblon Forever', libelle:'Bieres', montant:150.00, date:'2017-01-01'})
MERGE(personneLHF:Personne{nom:'Le Houblon Forever', position:'1 rue Gresset, 44000 Nantes'})
MERGE (transaction1)-[:VERS]->(personneLHF)
RETURN *
----

//graph

## Suppression des données

//hide
[source,cypher]
----
MATCH (n)
DETACH DELETE n
----

## Creation de noeuds et de relations
//hide
[source,cypher]
----
CREATE(t1:Transaction{libelle:'Bieres', montant:150.00, date:'2018-01-01'})
CREATE(t2:Transaction{libelle:'Bieres', montant:1000.00, date:'2018-01-02'})
CREATE(t3:Transaction{libelle:'Noel CE', montant:500.00, date:'2017-12-01'})
CREATE(p1:Personne{nom:'Bières d\'ailleurs'})
CREATE(p2:Personne{nom:'Jouet Club'})
CREATE (t1)-[:VERS]->(p1)
CREATE (t2)-[:VERS]->(p1)
CREATE (t3)-[:VERS]->(p2)
RETURN *
----

## Recherche de transactions

[source,cypher]
----
MATCH (t:Transaction)-[:VERS]->(b)
RETURN t, b
----

//graph_result



[source,cypher]
----
MATCH (t:Transaction)-[:VERS]->(b)
where t.montant > 200
RETURN t, beneficiaires
----

[source,cypher]
----
MATCH (t:Transaction)-[:VERS]->(b)
where t.montant > 150
and b.nom = 'Jouet Club'
RETURN t, b
----


## Import en masse

Todo cypher code import via csv, voir : https://neo4j.com/graphgist/importing-csv-files-with-cypher
Montrer l'import en batch de X élements USING PERIODIC COMMIT 500
LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/fnegre/z-papers/master/neo4j/csv/persons.csv" AS csvLine
MERGE (p:Personne {name: csvLine.personne})
MERGE (t:Transaction {libelle: csvLine.transactionLibelle, montant: csvLine.transactionMontant, date: csvLine.trasactionDate})
MERGE (t)-[:VERS]->(p)
## Ajout d'index

TODO Cypher code, création d'index

## Création de contraine unique

TODO Cyphr code : création de contrainte unique : éviter d'avoir plusieurs banques identiques par exemple
Exemple : CREATE CONSTRAINT ON (person:Person) ASSERT person.id IS UNIQUE

## Création white list et black list

TODO Cypher Code


## Identification des transactions frauduleuses

TODO Cypher Code avec


// Retour aux slides


## Présentation du count

cypher code : Count présence Consultant Z dans les locaux de l'agence lors de chaque virement frauduleux

// voir qu'Olivier Huber était présent dans les locaux Zenika lors de chaque virement frauduleux

Suspect n°1

