# Zenika Papers


## Transactions bancaires

TODO Cypher Code présentant la notion d'entité avec les entités + attributs transaction
Mot clef : CREATE, MERGE, RETURN
(sans relation)


## Transactions bancaires + relations

TODO Cypher Code présenter la notion de relations
mot clef : -[]->
(sans relation)


## Import en masse

Todo cypher code import via csv, voir : https://neo4j.com/graphgist/importing-csv-files-with-cypher
Montrer l'import en batch de X élements USING PERIODIC COMMIT 500

## Ajout d'index

TODO Cypher code, création d'index

## Création de contraine unique

TODO Cyphr code : création de contrainte unique : éviter d'avoir plusieurs banques identiques par exemple
Exemple : CREATE CONSTRAINT ON (person:Person) ASSERT person.id IS UNIQUE

## Création white list et black list

TODO Cypher Code


## Identification des transactions frauduleuses

TODO Cypher Code avec
mot clef MATCH



.Modélistion
//hide
[source,cypher]
----
MERGE (entite1:Entite {nom: 'Florian Negre', date_naissance: '19/05/1986'})
MERGE (entite2:Entite {nom: 'Vickrame'})
MERGE (contact1:Contact {date: '09/03/2018', type: 'Hangout', contenu: 'technozaures'})
MERGE (position1:Position {libelle: 'CBP', latitude: 47.22195, longitude: -1.6265260000000126})
MERGE (position2:Position {libelle: 'Quick', latitude: 47.22228089999999, longitude: -1.62676799999997})
MERGE (position3:Position {libelle: 'Société Générale de Banque aux Antilles Agence de Jarry', latitude: 16.2425049, longitude: -61.56335150000001})
MERGE (compte1:Compte {name:'Compte Florian', date:'01-01-2018 14h35'})
MERGE (transaction1:Transaction {credit: 10, date:'01-01-2018 14h35'})

MERGE (entite1) -[:POSSEDE]->(compte1)
MERGE (transaction1)-[:VERS]->(compte1)
MERGE (contact1)-[:PARTICIPANT]->(entite1)
MERGE (contact1)-[:PARTICIPANT]->(entite2)
MERGE (contact1)-[:LIEU]->(position1)

RETURN *
----


.Tout renvoyer
[source,cypher]
----
MATCH (n)
RETURN n;
----
