## Présentation Neo4J Browser

//
// https://neo4j.com/docs/cypher-refcard/current/
// Présenter les fonctionnalités qui ne sont pas supportés par Graphgist
// Créer des favoris / ou un répertoire de requêtes sur Neo4J Browser


## Graphe contenant jusqu'à la partie blacklist de pays

[source,cypher]
----
TODO
----


## Génération d'un graphe modele

[source,cypher]
```
// extraction modele
MATCH (a)-[r]->(b) WHERE labels(a) <> [] AND labels(b) <> []
RETURN DISTINCT head(labels(a)) AS This, type(r) as To, head(labels(b)) AS That LIMIT 100
```

[source,cypher]
```
 // generate the META-graph
 MATCH (a)-[r]->(b)
 WITH labels(a) AS a_labels,type(r) AS rel_type,labels(b) AS b_labels
 UNWIND a_labels as l
 UNWIND b_labels as l2
 MERGE (a:Node:Meta {name:l})
 MERGE (b:Node:Meta {name:l2})
 MERGE (a)-[:OUTGOING]->(:Relationship:Meta {name:rel_type})-[:INCOMING]->(b)
 RETURN distinct l as first_node, rel_type as connected_by, l2 as second_node
```

Puis faire `match(n:Node)--(m) return n,m`

## Requête permettant de trouver les requêtes frauduleuses (pays de la banque sur blacklist)

[source,cypher]
```
// Requetes frauduleuses
MATCH path =(t:Transaction)-[*..4]-(BlackList{flagBlackList:true})
RETURN nodes(path)
```

## Requête permettant de trouver la localisation des requêtes frauduleuses

TODO : à faire
[source,cypher]
```
```


## Requête permettant de filtrer les consultants arrivés avant les transactions frauduleuses

// documentation conversion date : https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_date_and_time_conversions

[source,cypher]
```
Match (c:Consultant)--(p:Personne)
WHERE apoc.date.parse(c.dateEmbauche,'s','yyyy-MM-dd') < apoc.date.parse('2017-06-01','s','yyyy-MM-dd')
RETURN c,p
```


## Requête permettant de filtrer les consultants à l'agence pendant transactions frauduleuses

TODO
[source,cypher]
```

```
// --> Olivier

## Requête permettant de trouver les consultants à l'étranger à l'ouverture du compte

TODO
[source,cypher]
```

```

// --> Julien


### Ajout des noeuds photos + localisation

TODO
[source,cypher]
```

```

### Distance entre la banque et les localisations des photos

.Distances entre deux points
[source,cypher]
----
Match(pos1:Position {libelle: 'Quick'})
Match (pos2:Position {libelle: 'CBP'})
WITH point({ longitude: pos1.longitude, latitude: pos1.latitude }) AS p1, point({ longitude: pos2.longitude, latitude: pos2.latitude }) AS p2
RETURN distance(p1,p2) AS dist
----

.Créer une relation entre chaque lieu contenant leur distance
[source,cypher]
----
Match(pos1:Position), (pos2:Position)
WHERE pos1.libelle <> pos2.libelle
WITH point({ longitude: pos1.longitude, latitude: pos1.latitude }) AS p1, point({ longitude: pos2.longitude, latitude: pos2.latitude }) AS p2, pos1, pos2
MERGE (pos1)-[:DISTANCE{valeur:distance(p1,p2)}]-(pos2)
----

.Créer une relation PROCHE entre chaque lieu dont la distance est inférieure à 10 km
[source,cypher]
----

----

### Requête : trouver qui est lié à la banque

TODO en cours
[source,cypher]
----
Match path = (p:Entite)-[*..4]-[PROCHE]-(l:Position{libelle:"Banque Offshore"})
return  nodes(path)
ORDER BY LENGTH(path) limit 1
----






### Aller plus loin
https://neo4j-contrib.github.io/neo4j-apoc-procedures/


## Commandes utilitaires pour nous

### Exporter ses favoris depuis le browser
Source : https://neo4j.com/developer/kb/how-do-i-export-cypher-favorites-recorded-in-the-browser/

[source,javascript]
----
var res = JSON.parse(localStorage.getItem('neo4j.documents'))
for (x in res) { console.log(res[x]['content']) }
----



### Supprimer le contenu de la base
[source,cypher]
----
MATCH (n)
DETACH DELETE n
----

### Renvoyer tout le contenu de la base
[source,cypher]
----
MATCH (n)
RETURN n
----

