## Présentation Neo4J Browser


//
// https://neo4j.com/docs/cypher-refcard/current/
// Présenter les fonctionnalités qui ne sont pas supportés par Graphgist
// Créer des favoris / ou un répertoire de requêtes sur Neo4J Browser


TODO : Ajouter des choses dans le local storage

## Graphe contenant jusqu'à la partie blacklist de pays



## Génération d'un graphe modele

[source,cypher]
```
// extraction modele
MATCH (a)-[r]->(b) WHERE labels(a) <> [] AND labels(b) <> []
RETURN DISTINCT head(labels(a)) AS This, type(r) as To, head(labels(b)) AS That LIMIT 10
```

[source,cypher]
```
 // generate the META-graph
 MATCH (a)-[r]->(b)
 WITH labels(a) AS a_labels,type(r) AS rel_type,labels(b) AS b_labels
 UNWIND a_labels as l
 UNWIND b_labels as l2
 MERGE (a:Node:Meta {name:l})
 MERGE (b:Node:Meta {name:l2})
 MERGE (a)-[:OUTGOING]->(:Relationship:Meta {name:rel_type})-[:INCOMING]->(b)
 RETURN distinct l as first_node, rel_type as connected_by, l2 as second_node
```

## Requête permettant de trouver les requêtes frauduleuses (pays de la banque sur blacklist)

TODO : A tester
[source,cypher]
```
MATCH path =(t:Transaction)-[*..*]-(b:Blacklist)
RETURN nodes(path)
```

## Requête permettant de trouver la localisation des requêtes frauduleuses

TODO : à faire
[source,cypher]
```
MATCH path =(t:Transaction)-[*..*]-(b:Blacklist)
RETURN nodes(path)
```


## Requête permettant de filtrer les consultants arrivés avant les transactions frauduleuses

TODO
[source,cypher]
```
Match (c:Consultant)
WHERE apoc.date.parse(c.dateEmbauche,['s'],['dd/MM//yyyy']) < 01/06/2018
RETURN c
```


## Requête permettant de filtrer les consultants à l'agence pendant transactions frauduleuses

TODO
[source,cypher]
```

```
// --> Olivier

## Requête permettant de trouver les consultatns à l'étranger à l'ouverture du compte

TODO
[source,cypher]
```

```

// --> Julien


### Ajout des noeuds photos + localisation

TODO
[source,cypher]
```

```

### Distance entre la banque et les localisations des photos

.Distances entre deux points
[source,cypher]
----
Match(pos1:Position {libelle: 'Quick'})
Match (pos2:Position {libelle: 'CBP'})
WITH point({ longitude: pos1.longitude, latitude: pos1.latitude }) AS p1, point({ longitude: pos2.longitude, latitude: pos2.latitude }) AS p2
RETURN distance(p1,p2) AS dist
----

.Créer une relation entre chaque lieu contenant leur distance
[source,cypher]
----
Match(pos1:Position), (pos2:Position)
WHERE pos1.libelle <> pos2.libelle
WITH point({ longitude: pos1.longitude, latitude: pos1.latitude }) AS p1, point({ longitude: pos2.longitude, latitude: pos2.latitude }) AS p2, pos1, pos2
MERGE (pos1)-[:DISTANCE{valeur:distance(p1,p2)}]-(pos2)
----


### Requête : trouver qui est lié à la banque

// Shortest Path
TODO en cours
[source,cypher]
----
Match path = (p:Entite)-[*..4]-(l:Position{libelle:"Quick"})
return  nodes(path)
ORDER BY LENGTH(path) limit 1
----



### Aller plus loin
https://neo4j-contrib.github.io/neo4j-apoc-procedures/










## Commandes utilitaires pour nous

### Exporter ses favoris depuis le browser
Source : https://neo4j.com/developer/kb/how-do-i-export-cypher-favorites-recorded-in-the-browser/

[source,javascript]
----
var res = JSON.parse(localStorage.getItem('neo4j.documents'))
for (x in res) { console.log(res[x]['content']) }
----



### Supprimer le contenu de la base
[source,cypher]
----
MATCH (n)
DETACH DELETE n
----

### Renvoyer tout le contenu de la base
[source,cypher]
----
MATCH (n)
RETURN n
----

